#!/usr/bin/env python3
"""Parse the workspace's career/trajectory.md into scoring criteria and render a
fixed-format Markdown score table.

score-opportunity shells out to this rather than freehand-formatting a
table itself, so the criteria list always matches trajectory.md verbatim
and the table layout never drifts between scoring sessions.
"""
import argparse
import json
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True  # never write into the plugin directory
sys.path.insert(0, str(Path(__file__).parent))
import workspace  # noqa: E402


def trajectory_path() -> Path:
    return workspace.require_root() / "career" / "trajectory.md"


SCORES = ["Meets", "Partial", "Fails", "Unknown"]
SCORE_EMOJI = {"Meets": "✅", "Partial": "⚠️", "Fails": "❌", "Unknown": "❓"}

# (heading in trajectory.md, category label, "bullets" or "paragraph")
CRITERIA_SECTIONS = [
    ("Must-Haves", "Must-Have", "bullets"),
    ("Must-Nots", "Must-Not", "bullets"),
    ("Short-Term Goal (Next Role)", "Short-Term Goal", "paragraph"),
]


def _section_body(trajectory_text, heading):
    # trajectory.md is hand-edited and regenerated by define-trajectory, whose
    # own SKILL.md documents these section names in different casing than the
    # literal headings it writes -- match case/whitespace-tolerantly so that
    # drift doesn't silently drop a whole criteria category.
    pattern = re.compile(
        rf"^##[ \t]+{re.escape(heading)}[ \t]*$(.*?)(?=^##[ \t]|\Z)",
        re.MULTILINE | re.DOTALL | re.IGNORECASE,
    )
    m = pattern.search(trajectory_text)
    return m.group(1).strip("\n") if m else None


def _parse_bullets(body):
    bullets = []
    for line in body.splitlines():
        stripped = line.strip()
        if stripped[:2] in ("- ", "* ", "+ "):
            bullets.append(stripped[2:].strip())
        elif stripped and bullets:
            bullets[-1] += " " + stripped
    return bullets


def _parse_paragraph(body):
    para = body.split("\n\n", 1)[0]
    return " ".join(para.split())


def parse_criteria(trajectory_text):
    criteria = []
    for heading, category, kind in CRITERIA_SECTIONS:
        body = _section_body(trajectory_text, heading)
        if body is None:
            raise ValueError(
                f"trajectory.md has no '## {heading}' section -- scoring "
                f"requires all of: {[h for h, _, _ in CRITERIA_SECTIONS]}"
            )
        slug = category.lower().replace(" ", "-")
        if kind == "bullets":
            bullets = _parse_bullets(body)
            if not bullets:
                raise ValueError(
                    f"'## {heading}' has no recognized bullet items "
                    f"(expected lines starting with '-', '*', or '+')"
                )
            for i, text in enumerate(bullets, start=1):
                criteria.append({"id": f"{slug}-{i}", "category": category, "text": text})
        else:
            text = _parse_paragraph(body)
            if not text:
                raise ValueError(f"'## {heading}' has no content")
            criteria.append({"id": slug, "category": category, "text": text})
    return criteria


def _escape_cell(text):
    return " ".join(text.split()).replace("|", "\\|")


def render_table(criteria, scores):
    criteria_by_id = {c["id"]: c for c in criteria}

    scores_by_id = {}
    for s in scores:
        if not isinstance(s, dict):
            raise ValueError(f"each score entry must be a JSON object, got {s!r}")
        rationale = s.get("rationale", "")
        if not isinstance(rationale, str):
            raise ValueError(f"'rationale' must be a string, got {rationale!r}")
        cid = s.get("id")
        if cid not in criteria_by_id:
            raise ValueError(f"unknown criterion id: {cid!r}")
        raw_score = s.get("score", "")
        normalized = raw_score.strip().title() if isinstance(raw_score, str) else raw_score
        if normalized not in SCORES:
            raise ValueError(
                f"invalid score {raw_score!r} for {cid!r}: must be one of {SCORES}"
            )
        scores_by_id[cid] = {"score": normalized, "rationale": rationale}

    missing = [c["id"] for c in criteria if c["id"] not in scores_by_id]
    if missing:
        raise ValueError(f"missing scores for criteria: {missing}")

    lines = ["| Criterion | Score | Rationale |", "| --- | --- | --- |"]
    for c in criteria:
        s = scores_by_id[c["id"]]
        criterion_cell = _escape_cell(f"**{c['category']}:** {c['text']}")
        score_cell = f"{SCORE_EMOJI[s['score']]} {s['score']}"
        rationale_cell = _escape_cell(s["rationale"])
        lines.append(f"| {criterion_cell} | {score_cell} | {rationale_cell} |")
    return "\n".join(lines)


def _read_trajectory():
    path = trajectory_path()
    if not path.exists():
        print(f"{path} not found", file=sys.stderr)
        sys.exit(1)
    return path.read_text()


def _load_criteria():
    try:
        return parse_criteria(_read_trajectory())
    except ValueError as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)


def cmd_criteria(args):
    criteria = _load_criteria()
    print(json.dumps(criteria, indent=2))


def cmd_render(args):
    criteria = _load_criteria()
    try:
        scores = json.load(sys.stdin)
    except json.JSONDecodeError as e:
        print(f"invalid JSON on stdin: {e}", file=sys.stderr)
        sys.exit(1)
    try:
        table = render_table(criteria, scores)
    except ValueError as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)
    print(table)


def build_parser():
    parser = argparse.ArgumentParser(
        description="Parse trajectory.md into scoring criteria and render a fixed-format score table"
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p_criteria = sub.add_parser("criteria", help="print criteria parsed from trajectory.md as JSON")
    p_criteria.set_defaults(func=cmd_criteria)

    p_render = sub.add_parser("render", help="read {id, score, rationale} JSON on stdin, print the score table")
    p_render.set_defaults(func=cmd_render)

    return parser


def main():
    parser = build_parser()
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
